name: SimpleSuite
main: pw.paradaux.simsuite.SimpleSuite
version: 0.025
commands:
    creative:
        description: Changes your Gamemode.
        permission: simple.gamemode
        permission-message: You do not have the necessary permissions to alter your gamemode.
    survival:
        description: Changes your Gamemode.
        permission: simple.gamemode
        permission-message: You do not have the necessary permissions to alter your gamemode.
    adventure:
        description: Changes your Gamemode.
        permission: simple.gamemode
        permission-message: You do not have the necessary permissions to alter your gamemode.
    spectator:
        description: Changes your Gamemode.
        permission: simple.gamemode
        permission-message: You do not have the necessary permissions to alter your gamemode.
    gmc:
        description: Changes your Gamemode.
        permission: simple.gamemode
        permission-message: You do not have the necessary permissions to alter your gamemode.
    gms:
        description: Changes your Gamemode.
        permission: simple.gamemode
        permission-message: You do not have the necessary permissions to alter your gamemode.
    gmc:
        description: Changes your Gamemode.
        permission: simple.gamemode
        permission-message: You do not have the necessary permissions to alter your gamemode.
    gma:
        description: Changes your Gamemode.
        permission: simple.gamemode
        permission-message: You do not have the necessary permissions to alter your gamemode.
    gmsp:
        description: Changes your Gamemode.
        permission: simple.gamemode
        permission-message: You do not have the necessary permissions to alter your gamemode.
    gm:
        description: Ihanges your Gamemode.
        permission: simple.gamemode
        permission-message: You do not have the necessary permissions to alter your gamemode.
    gamemode:
        description:
        permission: simple.gamemode
        permission-message: You do not have the necessary permissions to alter your gamemode.
        
    