name: SimpleSuite
main: pw.paradaux.simsuite.SimpleSuite
version: 0.04
commands:
    gamemode:
        description: Changes your Gamemode.
        aliases: [gm, gma, gms, gmc, gmsp,spectator, adventure, survival, creative]
    clearchat:
        description: Clears chat.
        aliases: [cc, clearc]
    simple:
        description: Information regarding SimpleSuite
    mutechat:
        description: Mutes the entire chat.
    msg:
        description: Message another player!
        aliases: [t, tell, w, whisper, message]